In [1]:
import pickle
import pandas as pd
import os

os.chdir('..')
os.chdir('..')
from analytics import RaceData
os.chdir('notebooks/simulation')

In [2]:
rd = RaceData()
rd.add_races_by_date('2026-01-01','2026-03-31',section_results=False)
rddf = rd.results_df.copy()

rddf['Finished'] = (rddf['Running / Reason Out'] == 'Running').astype(int)
rddf['Driver'] = rddf.Driver.str.replace(' (R)','')

In [3]:
with open('iters_0-4999_run2.pickle','rb') as f:
    iters = pickle.load(f)

dfs = []
for i,dfi in enumerate(iters):
    dfi.loc[dfi.Driver == 'Hauger, Denis','Driver'] = 'Hauger, Dennis'
    dfi.loc[dfi.Driver == 'Veekay, Rinus','Driver'] = 'VeeKay, Rinus'
    df = pd.concat([dfi,rddf[['Driver','Pos','SP','Finished','Pts']]]).fillna(0)
    df['Win'] = df.Pos.apply(lambda x: 1 if x==1 else 0)
    df['DNF'] = (1-df.Finished)
    df['Pole'] = df.SP.apply(lambda x: 1 if x==1 else 0)
    df['Indy500Winner'] = ((df.RaceInSeason ==7) & (df.Pos ==1)).astype(int)
    df_agg = df.groupby('Driver').agg(
        Pts = ('Pts','sum'),
        AvgSP = ('SP','mean'),
        FinishPct = ('Finished','mean'),
        AvgPos = ('Pos','mean'),
        Wins = ('Win','sum'),
        Indy500Winner = ('Indy500Winner','max'),
        DNFs = ('DNF','sum'),
        Poles = ('Pole','sum')
    ).reset_index()
    df_agg['Rank'] = df_agg['Pts'].rank(ascending=False)
    df_agg['iter'] = str(i)
    df_agg['Champion'] = (df_agg['Rank'] == 1).astype(int)
    dfs.append(df_agg)

dfa = pd.concat(dfs)

In [4]:
dfa.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max'),
        
).sort_values('AvgStandings')

,Avg_Pts,FinishRate,AvgSP,AvgFP,AvgWins,AvgPoles,AvgStandings,Championships,Indy500Wins,Best,Worst
Driver,,,,,,,,,,,
"Palou, Alex",657.373365,0.826056,5.013889,6.922567,5.5606,3.6802,1.2788,4061,1240,1.0,9.0
"O'Ward, Pato",566.295631,0.884844,6.129456,7.529644,1.9688,2.6482,2.7856,628,834,1.0,15.0
"Lundgaard, Christian",509.098744,0.884278,10.514467,8.697867,0.9182,0.8056,4.5758,91,385,1.0,14.0
"Kirkwood, Kyle",508.073269,0.881667,10.292100,9.133789,1.7822,0.4584,4.6174,70,158,1.0,15.0
"Malukas, David",490.364182,0.883756,6.474122,9.838278,1.2346,3.2178,5.4936,66,475,1.0,17.0
"McLaughlin, Scott",485.951872,0.883178,10.452178,10.109344,1.5592,1.8202,5.6978,72,241,1.0,19.0
"Newgarden, Josef",454.107223,0.882422,10.482622,10.883167,1.7362,1.0150,7.2172,8,56,1.0,19.0
"Armstrong, Marcus",430.756729,0.882400,8.440289,10.727844,0.4604,0.6428,8.4362,4,181,1.0,21.0
"Dixon, Scott",422.373497,0.828333,15.552011,11.078178,0.3282,0.0454,8.9154,0,126,2.0,20.0
"Rossi, Alexander",396.293887,0.881700,12.276967,11.872411,0.4262,0.3126,10.6234,0,234,2.0,22.0
"Ericsson, Marcus",387.668168,0.881500,10.892511,12.247656,0.2296,1.1790,11.1548,0,69,2.0,22.0
"Rosenqvist, Felix",380.211881,0.884022,10.228456,12.452111,0.2516,0.9144,11.7174,0,85,3.0,22.0
"Ferrucci, Santino",345.749035,0.826489,15.956011,13.808511,0.2852,0.3974,14.4066,0,190,2.0,24.0
"Simpson, Kyffin",345.200771,0.885100,15.364811,13.735011,0.1970,0.0456,14.4490,0,77,4.0,25.0
"Rasmussen, Christian",335.507949,0.826622,14.657678,14.482867,0.3030,0.1256,15.2578,0,164,2.0,25.0
"Power, Will",325.641149,0.826078,15.379689,14.545722,0.0762,0.0256,16.0652,0,23,6.0,25.0
"Grosjean, Romain",319.785965,0.768567,12.788200,14.880322,0.1660,0.1350,16.5498,0,38,6.0,25.0
"VeeKay, Rinus",319.159719,0.885022,15.919967,14.823044,0.2600,0.1434,16.6112,0,117,5.0,25.0
"Siegel, Nolan",304.891850,0.827144,13.344444,15.439522,0.0932,0.2346,17.7944,0,41,6.0,25.0
"Rahal, Graham",296.132219,0.883722,15.826933,15.582533,0.0086,0.0606,18.6072,0,1,10.0,24.0
"Robb, Sting Ray",279.492506,0.881433,18.950089,16.541244,0.1092,0.0004,19.7932,0,36,10.0,25.0
"Foster, Louis",260.659841,0.824100,16.432144,16.814833,0.0000,0.0000,21.2880,0,0,13.0,25.0
"Hauger, Dennis",226.510040,0.867289,20.000767,18.505833,0.0000,0.0000,23.4574,0,0,20.0,25.0
"Schumacher, Mick",218.767858,0.820633,16.442389,18.933244,0.0000,0.0002,23.9816,0,0,20.0,25.0
"Collet, Caio",214.871563,0.869333,20.268211,19.127278,0.0000,0.0110,24.2252,0,0,19.0,25.0
"Sato, Takuma",20.217690,0.769800,15.946800,14.762600,0.0154,0.0154,27.9048,0,77,26.0,31.0
"Carpenter, Ed",19.146177,0.760600,10.881800,16.068200,0.0128,0.0542,28.0692,0,64,26.0,31.0
"Hunter-Reay, Ryan",18.157642,0.779800,13.968000,16.030000,0.0114,0.0112,28.1924,0,57,26.0,31.0
"Daly, Conor",15.549583,0.765600,24.934600,17.832400,0.0052,0.0000,28.6744,0,26,26.0,31.0
"Castroneves, Helio",14.763329,0.784200,22.188200,18.429400,0.0010,0.0002,28.7410,0,5,26.0,31.0
"Harvey, Jack",11.715364,0.772600,27.633400,21.046600,0.0000,0.0000,29.4182,0,0,26.0,31.0

In [5]:
with open('./iters_0-4999_with_comps_run2.pickle','rb') as f:
    iters_wc = pickle.load(f)

dfs2 = []
for i,dfi in enumerate(iters_wc):
    dfi.loc[dfi.Driver == 'Hauger, Denis','Driver'] = 'Hauger, Dennis'
    dfi.loc[dfi.Driver == 'Veekay, Rinus','Driver'] = 'VeeKay, Rinus'
    df = pd.concat([dfi,rddf[['Driver','Pos','SP','Finished','Pts']]]).fillna(0)
    df['Win'] = df.Pos.apply(lambda x: 1 if x==1 else 0)
    df['DNF'] = (1-df.Finished)
    df['Pole'] = df.SP.apply(lambda x: 1 if x==1 else 0)
    df['Indy500Winner'] = ((df.RaceInSeason ==7) & (df.Pos ==1)).astype(int)
    df_agg = df.groupby('Driver').agg(
        Pts = ('Pts','sum'),
        AvgSP = ('SP','mean'),
        FinishPct = ('Finished','mean'),
        AvgPos = ('Pos','mean'),
        Wins = ('Win','sum'),
        Indy500Winner = ('Indy500Winner','max'),
        DNFs = ('DNF','sum'),
        Poles = ('Pole','sum')
    ).reset_index()
    df_agg['Rank'] = df_agg['Pts'].rank(ascending=False)
    df_agg['iter'] = f'{i}_wc'
    df_agg['Champion'] = (df_agg['Rank'] == 1).astype(int)
    dfs2.append(df_agg)

dfa2 = pd.concat(dfs2)

In [6]:
dfa2.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max')
).sort_values('AvgStandings')

,Avg_Pts,FinishRate,AvgSP,AvgFP,AvgWins,AvgPoles,AvgStandings,Championships,Indy500Wins,Best,Worst
Driver,,,,,,,,,,,
"Palou, Alex",655.838009,0.828133,5.042111,6.954744,5.5118,3.6922,1.2698,4091,1207,1.0,7.0
"O'Ward, Pato",563.881146,0.883456,6.171878,7.607278,1.9430,2.6524,2.7908,592,829,1.0,13.0
"Lundgaard, Christian",504.627413,0.882389,10.582867,8.853267,0.9144,0.7940,4.6510,69,379,1.0,16.0
"Kirkwood, Kyle",504.342147,0.882800,10.272900,9.281578,1.7838,0.4596,4.6608,69,187,1.0,14.0
"Malukas, David",489.414632,0.883900,6.529178,9.895011,1.2436,3.1886,5.4236,91,436,1.0,18.0
"McLaughlin, Scott",484.298920,0.885144,10.498567,10.167011,1.5556,1.8130,5.6396,71,250,1.0,19.0
"Newgarden, Josef",452.300748,0.881733,10.464844,10.970700,1.7732,1.0092,7.1052,12,66,1.0,20.0
"Armstrong, Marcus",428.736455,0.883267,8.486500,10.821833,0.4764,0.6504,8.3654,3,190,1.0,21.0
"Dixon, Scott",418.805374,0.827622,15.517433,11.216600,0.3386,0.0462,8.9420,0,86,2.0,21.0
"Rossi, Alexander",392.664034,0.883122,12.285344,12.022356,0.4338,0.3252,10.6304,2,265,1.0,23.0
"Ericsson, Marcus",383.786976,0.882033,10.890122,12.395233,0.2122,1.1708,11.2078,0,59,2.0,24.0
"Rosenqvist, Felix",375.550247,0.884889,10.254189,12.620544,0.2418,0.8948,11.8412,0,78,2.0,24.0
"Ferrucci, Santino",343.110364,0.827633,15.874544,13.944367,0.2966,0.3990,14.3832,0,188,3.0,25.0
"Simpson, Kyffin",340.838378,0.883311,15.328767,13.920133,0.2030,0.0422,14.5644,0,89,4.0,25.0
"Rasmussen, Christian",333.628356,0.830111,14.588256,14.574056,0.3118,0.1218,15.1682,0,174,4.0,25.0
"Power, Will",320.746080,0.827378,15.438378,14.747100,0.0708,0.0290,16.2670,0,28,6.0,25.0
"Grosjean, Romain",315.296724,0.767322,12.767900,15.073267,0.1554,0.1254,16.7606,0,32,5.0,25.0
"VeeKay, Rinus",315.048760,0.883944,15.908278,14.988300,0.2400,0.1380,16.8072,0,126,5.0,25.0
"Siegel, Nolan",299.033562,0.826467,13.373133,15.682700,0.0866,0.2250,18.2238,0,38,8.0,25.0
"Rahal, Graham",292.305523,0.882189,15.755333,15.769644,0.0080,0.0548,18.8548,0,1,8.0,25.0
"Robb, Sting Ray",276.453449,0.881911,18.801178,16.681656,0.1054,0.0002,20.3042,0,41,9.0,25.0
"Collet, Caio",258.517791,0.869956,19.749611,17.160833,0.0280,0.0228,21.9366,0,11,10.0,25.0
"Foster, Louis",255.441590,0.822544,16.336278,17.078967,0.0000,0.0000,22.3174,0,0,15.0,25.0
"Hauger, Dennis",247.921477,0.865422,20.336633,17.561533,0.0054,0.0000,22.8990,0,1,11.0,25.0
"Schumacher, Mick",229.824397,0.820733,16.836444,18.653611,0.0134,0.0678,23.9860,0,2,15.0,25.0
"Sato, Takuma",20.216870,0.776600,15.714400,14.741400,0.0184,0.0158,27.8530,0,92,26.0,31.0
"Carpenter, Ed",19.059155,0.777400,11.060400,16.075000,0.0154,0.0502,28.0606,0,77,26.0,31.0
"Hunter-Reay, Ryan",17.783387,0.775800,14.161400,16.336000,0.0072,0.0116,28.2124,0,36,26.0,31.0
"Daly, Conor",14.983520,0.770800,24.814600,18.215600,0.0048,0.0000,28.6964,0,24,26.0,31.0
"Castroneves, Helio",14.569853,0.777600,22.130800,18.714000,0.0016,0.0000,28.7378,0,8,26.0,31.0
"Harvey, Jack",11.463358,0.769600,27.486400,21.356200,0.0000,0.0000,29.4398,0,0,26.0,31.0

In [7]:
df_all = pd.concat([dfa,dfa2])
df_all['FinishPct2'] = df_all['FinishPct']*100
print(df_all.groupby('Driver').agg(
        Avg_Pts = ('Pts','mean'),
        FinishRate = ('FinishPct2','mean'),
        AvgSP = ('AvgSP','mean'),
        AvgFP = ('AvgPos','mean'),
        AvgWins = ('Wins','mean'),
        AvgPoles = ('Poles','mean'),
).sort_values('Avg_Pts',ascending=False).round(1).to_markdown())
print(df_all.groupby('Driver').agg(
        AvgStandings = ('Rank','mean'),
        Championships = ('Champion','sum'),
        Indy500Wins = ('Indy500Winner','sum'),
        Best = ('Rank','min'),
        Worst = ('Rank','max')
).sort_values('AvgStandings').round(1).to_markdown())

| Driver               |   Avg_Pts |   FinishRate |   AvgSP |   AvgFP |   AvgWins |   AvgPoles |
|:---------------------|----------:|-------------:|--------:|--------:|----------:|-----------:|
| Palou, Alex          |     656.6 |         82.7 |     5   |     6.9 |       5.5 |        3.7 |
| O'Ward, Pato         |     565.1 |         88.4 |     6.2 |     7.6 |       2   |        2.7 |
| Lundgaard, Christian |     506.9 |         88.3 |    10.5 |     8.8 |       0.9 |        0.8 |
| Kirkwood, Kyle       |     506.2 |         88.2 |    10.3 |     9.2 |       1.8 |        0.5 |
| Malukas, David       |     489.9 |         88.4 |     6.5 |     9.9 |       1.2 |        3.2 |
| McLaughlin, Scott    |     485.1 |         88.4 |    10.5 |    10.1 |       1.6 |        1.8 |
| Newgarden, Josef     |     453.2 |         88.2 |    10.5 |    10.9 |       1.8 |        1   |
| Armstrong, Marcus    |     429.7 |         88.3 |     8.5 |    10.8 |       0.5 |        0.6 |
| Dixon, Scott         |     420.6 |         82.8 |    15.5 |    11.1 |       0.3 |        0   |
| Rossi, Alexander     |     394.5 |         88.2 |    12.3 |    11.9 |       0.4 |        0.3 |
| Ericsson, Marcus     |     385.7 |         88.2 |    10.9 |    12.3 |       0.2 |        1.2 |
| Rosenqvist, Felix    |     377.9 |         88.4 |    10.2 |    12.5 |       0.2 |        0.9 |
| Ferrucci, Santino    |     344.4 |         82.7 |    15.9 |    13.9 |       0.3 |        0.4 |
| Simpson, Kyffin      |     343   |         88.4 |    15.3 |    13.8 |       0.2 |        0   |
| Rasmussen, Christian |     334.6 |         82.8 |    14.6 |    14.5 |       0.3 |        0.1 |
| Power, Will          |     323.2 |         82.7 |    15.4 |    14.6 |       0.1 |        0   |
| Grosjean, Romain     |     317.5 |         76.8 |    12.8 |    15   |       0.2 |        0.1 |
| VeeKay, Rinus        |     317.1 |         88.4 |    15.9 |    14.9 |       0.2 |        0.1 |
| Siegel, Nolan        |     302   |         82.7 |    13.4 |    15.6 |       0.1 |        0.2 |
| Rahal, Graham        |     294.2 |         88.3 |    15.8 |    15.7 |       0   |        0.1 |
| Robb, Sting Ray      |     278   |         88.2 |    18.9 |    16.6 |       0.1 |        0   |
| Foster, Louis        |     258.1 |         82.3 |    16.4 |    16.9 |       0   |        0   |
| Hauger, Dennis       |     237.2 |         86.6 |    20.2 |    18   |       0   |        0   |
| Collet, Caio         |     236.7 |         87   |    20   |    18.1 |       0   |        0   |
| Schumacher, Mick     |     224.3 |         82.1 |    16.6 |    18.8 |       0   |        0   |
| Sato, Takuma         |      20.2 |         77.3 |    15.8 |    14.8 |       0   |        0   |
| Carpenter, Ed        |      19.1 |         76.9 |    11   |    16.1 |       0   |        0.1 |
| Hunter-Reay, Ryan    |      18   |         77.8 |    14.1 |    16.2 |       0   |        0   |
| Daly, Conor          |      15.3 |         76.8 |    24.9 |    18   |       0   |        0   |
| Castroneves, Helio   |      14.7 |         78.1 |    22.2 |    18.6 |       0   |        0   |
| Harvey, Jack         |      11.6 |         77.1 |    27.6 |    21.2 |       0   |        0   |
| Driver               |   AvgStandings |   Championships |   Indy500Wins |   Best |   Worst |
|:---------------------|---------------:|----------------:|--------------:|-------:|--------:|
| Palou, Alex          |            1.3 |            8152 |          2447 |      1 |       9 |
| O'Ward, Pato         |            2.8 |            1220 |          1663 |      1 |      15 |
| Lundgaard, Christian |            4.6 |             160 |           764 |      1 |      16 |
| Kirkwood, Kyle       |            4.6 |             139 |           345 |      1 |      15 |
| Malukas, David       |            5.5 |             157 |           911 |      1 |      18 |
| McLaughlin, Scott    |            5.7 |             143 |           491 |      1 |      19 |
| Newgarden, Josef     |            7.2 |              20 |           122 |      1 |      20 |
| Armstrong, Marcus    |            8.4 |               7 |           371 |      1 |      21 |
| Dixon, Scott         |            8.9 |               0 |           212 |      2 |      21 |
| Rossi, Alexander     |           10.6 |               2 |           499 |      1 |      23 |
| Ericsson, Marcus     |           11.2 |               0 |           128 |      2 |      24 |
| Rosenqvist, Felix    |           11.8 |               0 |           163 |      2 |      24 |
| Ferrucci, Santino    |           14.4 |               0 |           378 |      2 |      25 |
| Simpson, Kyffin      |           14.5 |               0 |           166 |      4 |      25 |
| Rasmussen, Christian |           15.2 |               0 |           338 |      2 |      25 |
| Power, Will          |           16.2 |               0 |            51 |      6 |      25 |
| Grosjean, Romain     |           16.7 |               0 |            70 |      5 |      25 |
| VeeKay, Rinus        |           16.7 |               0 |           243 |      5 |      25 |
| Siegel, Nolan        |           18   |               0 |            79 |      6 |      25 |
| Rahal, Graham        |           18.7 |               0 |             2 |      8 |      25 |
| Robb, Sting Ray      |           20   |               0 |            77 |      9 |      25 |
| Foster, Louis        |           21.8 |               0 |             0 |     13 |      25 |
| Collet, Caio         |           23.1 |               0 |            11 |     10 |      25 |
| Hauger, Dennis       |           23.2 |               0 |             1 |     11 |      25 |
| Schumacher, Mick     |           24   |               0 |             2 |     15 |      25 |
| Sato, Takuma         |           27.9 |               0 |           169 |     26 |      31 |
| Carpenter, Ed        |           28.1 |               0 |           141 |     26 |      31 |
| Hunter-Reay, Ryan    |           28.2 |               0 |            93 |     26 |      31 |
| Daly, Conor          |           28.7 |               0 |            50 |     26 |      31 |
| Castroneves, Helio   |           28.7 |               0 |            13 |     26 |      31 |
| Harvey, Jack         |           29.4 |               0 |             0 |     26 |      31 |

In [19]:
dfdiff = pd.read_csv('pred differences.csv')
print(dfdiff[['**Driver**', 'Average Season Points', 'Average Finishing Position',
       'Wins per Season', 'Average Championship Standing',
       '  Total Championships', ' Total Indy 500 Wins']].sort_values('Average Season Points',ascending=False).to_markdown(index=False))

| **Driver**               |   Average Season Points |   Average Finishing Position |   Wins per Season |   Average Championship Standing |     Total Championships |    Total Indy 500 Wins |
|:-------------------------|------------------------:|-----------------------------:|------------------:|--------------------------------:|------------------------:|-----------------------:|
| **Kirkwood, Kyle**       |                    65.1 |                         -1.9 |               0.9 |                            -3.5 |                     117 |                    104 |
| **Ericsson, Marcus**     |                    40.2 |                         -1.7 |               0   |                            -4.6 |                       0 |                     42 |
| **Malukas, David**       |                    39.5 |                         -1.5 |               0.1 |                            -2.2 |                     109 |                    313 |
| **Hauger, Dennis**       |                    17.4 |                         -1.1 |               0   |                            -1   |                       0 |                     10 |
| **Newgarden, Josef**     |                    16   |                         -0.7 |               0.8 |                            -1.3 |                       3 |                     23 |
| **Palou, Alex**          |                    12.8 |                          0   |               1.1 |                            -0.2 |                    1386 |                    405 |
| **Armstrong, Marcus**    |                    10.7 |                         -0.9 |               0   |                            -1.2 |                       1 |                     78 |
| **Collet, Caio**         |                    10.4 |                         -0.8 |               0   |                            -0.5 |                       0 |                    -10 |
| **Lundgaard, Christian** |                     4.2 |                         -0.5 |              -0.3 |                            -0.2 |                     -89 |                   -115 |
| **Rahal, Graham**        |                    -0.3 |                          0   |               0   |                            -1.2 |                       0 |                     -1 |
| **Rossi, Alexander**     |                    -5.8 |                         -0.4 |              -0.1 |                            -0.5 |                       0 |                    -31 |
| **Power, Will**          |                    -6.2 |                          0.1 |               0   |                            -0.9 |                       0 |                      3 |
| **Schumacher, Mick**     |                    -9.5 |                          0.4 |               0   |                             0.6 |                       0 |                     -1 |
| **Foster, Louis**        |                   -11.9 |                          0.4 |               0   |                             0.2 |                       0 |                      0 |
| **Rosenqvist, Felix**    |                   -14.5 |                          0.1 |              -0.1 |                             0.1 |                       0 |                    -13 |
| **McLaughlin, Scott**    |                   -14.8 |                          0   |              -0.3 |                             0.6 |                    -195 |                    108 |
| **Grosjean, Romain**     |                   -19.4 |                          0.7 |               0   |                             0.2 |                       0 |                     17 |
| **O'Ward, Pato**         |                   -22.4 |                          0   |              -0.5 |                             0.5 |                   -1286 |                   -384 |
| **Veekay, Rinus**        |                   -26.4 |                          0.5 |              -0.2 |                             0.8 |                       0 |                    -97 |
| **Ferrucci, Santino**    |                   -34.8 |                          0.9 |              -0.2 |                             1.6 |                      -1 |                   -172 |
| **Rasmussen, Christian** |                   -42.1 |                          1.5 |              -0.1 |                             2.2 |                       0 |                    -25 |
| **Robb, Sting Ray**      |                   -44.9 |                          1.8 |              -0.1 |                             2.4 |                       0 |                    -55 |
| **Dixon, Scott**         |                   -45.5 |                          0.9 |              -0.4 |                             2.4 |                     -45 |                   -202 |
| **Simpson, Kyffin**      |                   -47   |                          1.2 |              -0.2 |                             2.6 |                       0 |                    -55 |
| **Siegel, Nolan**        |                   -58.5 |                          2.2 |              -0.1 |                             3.6 |                       0 |                    -69 |